# Generated by Django 6.0.4 on 2026-05-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Adresi")),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MAC Adresi"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cihaz Adı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Bilinmiyor"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(default=0, verbose_name="Risk Skoru"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="İlk Görülme"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Son Görülme"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Olay Başlığı"),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Bilgi"),
                            ("warning", "Uyarı"),
                            ("danger", "Tehlike"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("new_device", "Yeni Cihaz"),
                            ("port_scan", "Port Tarama"),
                            ("arp_spoof", "ARP Spoofing"),
                            ("suspicious_traffic", "Şüpheli Trafik"),
                            ("system", "Sistem"),
                        ],
                        max_length=50,
                        verbose_name="Uyarı Tipi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Düşük"),
                            ("medium", "Orta"),
                            ("high", "Yüksek"),
                            ("critical", "Kritik"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Seviye",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Çözüldü mü?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="dashboard.device",
                        verbose_name="İlgili Cihaz",
                    ),
                ),
            ],
        ),
    ]
