# Generated by Django 6.0.6 on 2026-06-22 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_alert_id_alter_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(verbose_name='Kaynak IP')),
                ('service', models.CharField(choices=[('ssh', 'SSH'), ('http', 'HTTP'), ('ftp', 'FTP')], max_length=20, verbose_name='Servis')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Kullanici adi')),
                ('command', models.CharField(blank=True, max_length=255, verbose_name='Kaydedilen istek/komut')),
                ('is_mock', models.BooleanField(default=True, verbose_name='Mock veri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma tarihi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_range', models.CharField(default='demo-network', max_length=64, verbose_name='Ag araligi')),
                ('status', models.CharField(choices=[('demo', 'Demo'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz')], default='demo', max_length=20, verbose_name='Durum')),
                ('devices_found', models.PositiveIntegerField(default=0, verbose_name='Bulunan cihaz')),
                ('is_mock', models.BooleanField(default=True, verbose_name='Mock veri')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Aciklama')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Baslangic')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitis')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(default='low', max_length=20, verbose_name='Risk seviyesi')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Risk skoru')),
                ('security_score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Guvenlik puani')),
                ('active_alerts', models.PositiveIntegerField(default=0, verbose_name='Aktif uyari')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayit zamani')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Anahtar')),
                ('value', models.CharField(max_length=255, verbose_name='Deger')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Aciklama')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterModelOptions(
            name='securityevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Kaynak IP'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_mac',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kaynak MAC'),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('investigating', 'Inceleniyor'), ('resolved', 'Cozuldu')], default='active', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='Guvenilir'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Uretici'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Hedef IP'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='destination_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hedef port'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('network', 'Ag Olayi'), ('port_scan', 'Port Tarama Tespiti'), ('arp_anomaly', 'ARP Anomalisi'), ('brute_force', 'Kaba Kuvvet Tespiti'), ('honeypot', 'Honeypot'), ('system', 'Sistem')], default='system', max_length=50, verbose_name='Olay tipi'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, verbose_name='Protokol'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Risk skoru'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Kaynak IP'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='source_mac',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kaynak MAC'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('new_device', 'Yeni Cihaz'), ('port_scan', 'Port Tarama Tespiti'), ('arp_spoof', 'ARP Anomali Tespiti'), ('brute_force', 'Kaba Kuvvet Tespiti'), ('suspicious_traffic', 'Supheli Trafik'), ('honeypot', 'Honeypot'), ('system', 'Sistem')], max_length=50, verbose_name='Uyari tipi'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dashboard.device'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Cozuldu'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Dusuk'), ('medium', 'Orta'), ('high', 'Yuksek'), ('critical', 'Kritik')], default='low', max_length=20, verbose_name='Seviye'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Baslik'),
        ),
        migrations.AlterField(
            model_name='device',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ilk gorulme'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cihaz adi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP adresi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='Son gorulme'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC adresi'),
        ),
        migrations.AlterField(
            model_name='device',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Risk skoru'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='description',
            field=models.TextField(verbose_name='Aciklama'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='level',
            field=models.CharField(choices=[('info', 'Bilgi'), ('warning', 'Uyari'), ('danger', 'Tehlike')], default='info', max_length=20, verbose_name='Seviye'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Olay basligi'),
        ),
    ]
