# Generated by Django 6.0.6 on 2026-06-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_honeypotevent_networkscan_risksnapshot_systemsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotevent',
            name='destination_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hedef port'),
        ),
        migrations.AddField(
            model_name='honeypotevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Log kimligi'),
        ),
        migrations.AddField(
            model_name='honeypotevent',
            name='login_success',
            field=models.BooleanField(default=False, verbose_name='Giris basarili'),
        ),
        migrations.AddField(
            model_name='honeypotevent',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ham log'),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='networkscan',
            name='scan_method',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tarama yontemi'),
        ),
    ]
