# Generated by Django 6.0.6 on 2026-06-23 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_honeypotevent_destination_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringCycleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Baslangic')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitis')),
                ('status', models.CharField(choices=[('completed', 'Tamamlandi'), ('partial', 'Kismi'), ('failed', 'Basarisiz')], default='failed', max_length=20, verbose_name='Durum')),
                ('scan_status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandi'), ('skipped', 'Atlandi'), ('failed', 'Basarisiz')], default='pending', max_length=20, verbose_name='Scan durumu')),
                ('scan_found_devices', models.PositiveIntegerField(default=0, verbose_name='Bulunan cihaz')),
                ('scan_new_devices', models.PositiveIntegerField(default=0, verbose_name='Yeni cihaz')),
                ('honeypot_status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandi'), ('skipped', 'Atlandi'), ('failed', 'Basarisiz')], default='pending', max_length=20, verbose_name='Honeypot durumu')),
                ('honeypot_read_lines', models.PositiveIntegerField(default=0, verbose_name='Okunan log satiri')),
                ('honeypot_created_events', models.PositiveIntegerField(default=0, verbose_name='Eklenen honeypot olayi')),
                ('honeypot_duplicates', models.PositiveIntegerField(default=0, verbose_name='Duplicate honeypot olayi')),
                ('honeypot_parse_errors', models.PositiveIntegerField(default=0, verbose_name='Honeypot parse hatasi')),
                ('analysis_status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandi'), ('skipped', 'Atlandi'), ('failed', 'Basarisiz')], default='pending', max_length=20, verbose_name='Analiz durumu')),
                ('arp_alerts', models.PositiveIntegerField(default=0, verbose_name='ARP bulgusu')),
                ('port_alerts', models.PositiveIntegerField(default=0, verbose_name='Port bulgusu')),
                ('ssh_alerts', models.PositiveIntegerField(default=0, verbose_name='SSH bulgusu')),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Risk skoru')),
                ('error_summary', models.TextField(blank=True, verbose_name='Hata ozeti')),
                ('raw_summary', models.JSONField(blank=True, default=dict, verbose_name='Ham ozet')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
