# Generated by Django 6.0.6 on 2026-06-23 16:00

import django.utils.timezone
from django.db import migrations, models


def migrate_investigating_to_acknowledged(apps, schema_editor):
    Alert = apps.get_model("dashboard", "Alert")
    Alert.objects.filter(status="investigating").update(status="acknowledged")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_monitoringcyclerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Guncellenme tarihi'),
        ),
        migrations.RunPython(migrate_investigating_to_acknowledged, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Guncellenme tarihi'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('acknowledged', 'Incelendi'), ('resolved', 'Cozuldu')], default='active', max_length=20, verbose_name='Durum'),
        ),
    ]
