# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alert_updated_at_alter_alert_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("new_device", "Yeni Cihaz"),
                    ("port_scan", "Port Tarama Tespiti"),
                    ("arp_spoof", "ARP Anomali Tespiti"),
                    ("brute_force", "Kaba Kuvvet Tespiti"),
                    ("dos_suspected", "DoS Şüphesi"),
                    ("ssh_port_open", "SSH Portu Açık"),
                    ("telnet_port_open", "Telnet Portu Açık"),
                    ("database_port_open", "Veritabanı Portu Açık"),
                    ("risky_port", "Riskli Port"),
                    ("suspicious_traffic", "Supheli Trafik"),
                    ("honeypot", "Honeypot"),
                    ("system", "Sistem"),
                ],
                max_length=50,
                verbose_name="Uyari tipi",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("partial", "Kısmen algılandı"),
                    ("unknown", "Bilinmiyor"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("network", "Ag Olayi"),
                    ("port_scan", "Port Tarama Tespiti"),
                    ("arp_anomaly", "ARP Anomalisi"),
                    ("brute_force", "Kaba Kuvvet Tespiti"),
                    ("dos_suspected", "DoS Şüphesi"),
                    ("open_port", "Açık Port"),
                    ("honeypot", "Honeypot"),
                    ("system", "Sistem"),
                ],
                default="system",
                max_length=50,
                verbose_name="Olay tipi",
            ),
        ),
    ]
