# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_explainable_security_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("port", models.PositiveIntegerField(verbose_name="Port")),
                ("protocol", models.CharField(default="tcp", max_length=20, verbose_name="Protokol")),
                ("service_name", models.CharField(blank=True, max_length=80, verbose_name="Servis")),
                ("source", models.CharField(blank=True, max_length=80, verbose_name="Kaynak")),
                ("first_seen", models.DateTimeField(auto_now_add=True, verbose_name="İlk görülme")),
                ("last_seen", models.DateTimeField(auto_now=True, verbose_name="Son görülme")),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_ports",
                        to="dashboard.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device__ip_address", "port"],
            },
        ),
        migrations.AddConstraint(
            model_name="openport",
            constraint=models.UniqueConstraint(
                fields=("device", "port", "protocol"), name="unique_open_port_per_device"
            ),
        ),
    ]
