# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_openport"),
    ]

    operations = [
        migrations.AddField(
            model_name="honeypotevent",
            name="event_type",
            field=models.CharField(
                choices=[("connection", "Bağlantı"), ("auth_failure", "Başarısız giriş"), ("request", "İstek")],
                default="connection",
                max_length=30,
                verbose_name="Olay tipi",
            ),
        ),
        migrations.AddField(
            model_name="honeypotevent",
            name="protocol",
            field=models.CharField(blank=True, default="tcp", max_length=20, verbose_name="Protokol"),
        ),
        migrations.AddField(
            model_name="honeypotevent",
            name="source_port",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Kaynak port"),
        ),
        migrations.AddField(
            model_name="honeypotevent",
            name="source_type",
            field=models.CharField(blank=True, default="OpenCanary logu", max_length=80, verbose_name="Kaynak veri turu"),
        ),
        migrations.AlterField(
            model_name="honeypotevent",
            name="service",
            field=models.CharField(
                choices=[("ssh", "SSH"), ("http", "HTTP"), ("ftp", "FTP"), ("telnet", "Telnet")],
                max_length=20,
                verbose_name="Servis",
            ),
        ),
        migrations.CreateModel(
            name="ArpObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP adresi")),
                ("mac_address", models.CharField(max_length=50, verbose_name="MAC adresi")),
                ("source", models.CharField(blank=True, default="ARP gözlemi", max_length=80, verbose_name="Kaynak")),
                ("is_gateway", models.BooleanField(default=False, verbose_name="Gateway")),
                ("observed_at", models.DateTimeField(auto_now_add=True, verbose_name="Gözlem zamanı")),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
    ]
