"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent

load_dotenv(PROJECT_ROOT / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bq^)(#bkbz9(0xx=3fw$s-ppxm7(0t0j#lendwiv+w(8^ewo5u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Bu bbir denemedir
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     'accounts',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"

# GuardianNet runtime configuration. Environment variables override these safe defaults.
GUARDIANNET_MODE_ENV = os.getenv("GUARDIANNET_MODE")
LOCAL_SUBNET_ENV = os.getenv("LOCAL_SUBNET")
GUARDIANNET_MODE = (GUARDIANNET_MODE_ENV or "real").strip().lower()
LOCAL_SUBNET = (LOCAL_SUBNET_ENV or "").strip()
SCAN_INTERVAL_SECONDS = int(os.getenv("SCAN_INTERVAL_SECONDS", "300"))
OPENCANARY_LOG_PATH = os.getenv("OPENCANARY_LOG_PATH", str(BASE_DIR.parent.parent / "logs" / "opencanary.log"))
ENABLE_REAL_SCAN = env_bool("ENABLE_REAL_SCAN", True)
ENABLE_HONEYPOT_LOGS = env_bool("ENABLE_HONEYPOT_LOGS", True)
NETWORK_SCAN_MAX_HOSTS = int(os.getenv("NETWORK_SCAN_MAX_HOSTS", "1024"))
MONITORING_CYCLE_SCAN_LIMIT = os.getenv("MONITORING_CYCLE_SCAN_LIMIT", "10").strip()
PORT_SCAN_THRESHOLD = int(os.getenv("PORT_SCAN_THRESHOLD", "6"))
HONEYPOT_PORT_SCAN_THRESHOLD = int(os.getenv("HONEYPOT_PORT_SCAN_THRESHOLD", "3"))
HONEYPOT_PORT_SCAN_WINDOW_SECONDS = int(os.getenv("HONEYPOT_PORT_SCAN_WINDOW_SECONDS", "60"))
BRUTE_FORCE_THRESHOLD = int(os.getenv("BRUTE_FORCE_THRESHOLD", "5"))
DOS_REQUEST_THRESHOLD = int(os.getenv("DOS_REQUEST_THRESHOLD", "20"))
DETECTION_WINDOW_MINUTES = int(os.getenv("DETECTION_WINDOW_MINUTES", "10"))
